import { style } from '@vanilla-extract/css';

export const BDBM = {
  Body: style({
    width: '100%',
    minHeight: '400px',
  }),
  Title: style({
    fontSize: '40px',
    fontWeight: '800',
    color: '#1a202c',
    lineHeight: '1.3',
    marginBottom: '32px',
    wordBreak: 'break-word',
    letterSpacing: '-1px',
  }),
  Contents: style({
    fontSize: '17px',
    lineHeight: '1.8',
    color: '#2d3748',
    paddingTop: '20px',
    paddingBottom: '80px',
    minHeight: '200px',
    fontWeight: '400',
  }),
  IconWrapper: style({
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    width: '80px',
    height: '80px',
    borderRadius: '20px',
    backgroundColor: '#f7fafc',
    transition: 'all 0.2s ease',
    cursor: 'pointer',
    ':hover': {
      backgroundColor: '#edf2f7',
      transform: 'translateY(-4px)',
    },
  }),
  Youtube: style({
    margin: '40px auto',
    borderRadius: '16px',
    overflow: 'hidden',
    boxShadow: '0 8px 30px rgba(0,0,0,0.06)',
  }),
  LikeWrapper: style({
    marginTop: '60px',
    paddingTop: '40px',
    borderTop: '1px solid #edf2f7',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    gap: '32px',
  }),
  LocationIcon: style({}),
  LikeIcon: style({
    fontSize: '28px',
    color: '#ecc94b',
    marginBottom: '8px',
  }),
  DislikeIcon: style({
    fontSize: '28px',
    color: '#a0aec0',
    marginBottom: '8px',
  }),
  LikeCount: style({
    fontSize: '15px',
    fontWeight: '700',
    color: '#d69e2e',
  }),
  DislikeCount: style({
    fontSize: '15px',
    fontWeight: '700',
    color: '#718096',
  }),
  ImageWrapper: style({
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '24px',
    marginBottom: '50px',
  }),
  Image: style({
    width: '100%',
    maxWidth: '800px',
    height: 'auto',
    borderRadius: '16px',
    boxShadow: '0 4px 20px rgba(0,0,0,0.04)',
    border: '1px solid #f7fafc',
  }),
};
