import { style } from '@vanilla-extract/css';

export const PF = {
  CustomBody: style({
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  }),
  Wrapper: style({
    width: '1200px',
    border: 'none',
    margin: '100px',
    padding: '80px 102px 100px 102px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    boxShadow: '0px 0px 10px gray',
  }),
  Title: style({
    fontFamily: 'Arial, Helvetica, sans-serif',
    fontSize: '36px',
    fontWeight: 'bold',
  }),
  WriterWrapper: style({
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: '40px',
  }),
  Writer: style({
    width: '486px',
    height: '52px',
    paddingLeft: '16px',
    border: '1px solid #bdbdbd',
  }),
  Password: style({
    width: '486px',
    height: '52px',
    paddingLeft: '16px',
    border: '1px solid #bdbdbd',
  }),
  Label: style({
    paddingBottom: '16px',
    fontSize: '16px',
    fontWeight: 500,
  }),
  InputWrapper: style({
    paddingTop: '40px',
    width: '100%',
  }),
  Subject: style({
    width: '996px',
    height: '52px',
    paddingLeft: '16px',
    border: '1px solid #bdbdbd',
  }),
  Contents: style({
    width: '996px',
    height: '480px',
    padding: '14px 16px',
    border: '1px solid #bdbdbd',
  }),
  ZipcodeWrapper: style({
    display: 'flex',
    flexDirection: 'row',
  }),
  Zipcode: style({
    width: '77px',
    height: '52px',
    paddingLeft: '16px',
    border: '1px solid #bdbdbd',
  }),
  SearchButton: style({
    width: '124px',
    height: '52px',
    marginLeft: '16px',
    backgroundColor: 'black',
    cursor: 'pointer',
    color: 'white',
    border: 'none',
  }),
  Address: style({
    width: '996px',
    height: '52px',
    marginTop: '16px',
    paddingLeft: '16px',
    border: '1px solid #bdbdbd',
  }),
  Youtube: style({
    width: '996px',
    height: '52px',
    paddingLeft: '16px',
    border: '1px solid #bdbdbd',
  }),
  ImageWrapper: style({
    width: '996px',
    paddingTop: '40px',
  }),
  DropzoneContainer: style({
    border: '1px dashed #ccc',
    padding: '16px',
    textAlign: 'center',
    cursor: 'pointer',
  }),
  ImageBox: style({
    display: 'flex',
    flexDirection: 'row',
    marginTop: '20px',
    flexWrap: 'wrap',
    gap: '24px',
  }),
  ImagePreviewWrapper: style({
    position: 'relative',
    marginRight: '16px',
  }),
  ImagePreview: style({
    width: '100px',
    height: '100px',
    objectFit: 'cover',
  }),
  ImagePlaceholder: style({
    width: '100px',
    height: '100px',
    background: '#f2f2f2',
  }),
  ImageDeleteButton: style({
    position: 'absolute',
    top: '4px',
    right: '4px',
    padding: '0 6px',
    backgroundColor: '#ff4d4f',
    color: 'white',
    border: 'none',
    cursor: 'pointer',
    fontSize: '12px',
    height: '24px',
    width: '24px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '50%',
  }),
  OptionWrapper: style({
    width: '996px',
    paddingTop: '40px',
  }),
  RadioButton: style({
    cursor: 'pointer',
  }),
  RadioLabel: style({
    marginLeft: '8px',
    marginRight: '20px',
    fontWeight: 500,
    cursor: 'pointer',
  }),
  ButtonWrapper: style({
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    paddingTop: '80px',
  }),
  SubmitButton: style({
    width: '179px',
    height: '52px',
    border: 'none',
    fontSize: '16px',
    fontWeight: 500,
    margin: '0px 12px',
    cursor: 'pointer',
  }),
  Error: style({
    paddingTop: '10px',
    fontSize: '14px',
    color: 'red',
  }),
};
